[package]
name = "tetris_godot_binding"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
godot = "0.2.4"
tetris_game_logic = { path = "../tetris_game_logic" }
m2s2-math = { path = "../../m2s2-rust-math/m2s2-math" }
